DCBIA-OrthoLab/SlicerAutomatedDentalTools

- ALI/ALI.py
- ALI_CBCT/ALI_CBCT.py
- ALI_IOS/ALI_IOS.py
- AMASSS/AMASSS.py
- AMASSS_CLI/AMASSS_CLI.py
Allow the user to put a folder as input in ALI extension (Reuse of the AMASSS function)
> COMP: Fix compilation with a folder as input

- ALI/ALI.py
- ALI_IOS/ALI_IOS.py
@juanprietob @hina-shah 
1. Folder as input works now both for ALI IOS and CBCT
2. Fix a compilation issue (Fragments object unpacking)
> COMP: Fix both issues with ALI_IOS

- ALI_CBCT/ALI_CBCT.py
- ALI_IOS/ALI_IOS.py
- AMASSS_CLI/AMASSS_CLI.py
> COMP: Pip install Instances required to compilation (AMASSS, ALI_CBCT)

- ALI_IOS/ALI_IOS.py
- README.md
> BUG: ALI_IOS can use output of SlicerDentalModelSeg

- ALI_IOS/ALI_IOS.py
> BUG : remove .lower

- AMASSS/AMASSS.py
- AMASSS_CLI/AMASSS_CLI.py
The Cranial Base Mask Segmentation has been implemented:
- Another "Masks" tab has been added with the Cranial Base Option
- New models can be downloaded directly through Slicer
@juanprietob @allemangD @luciacev
> ENH: CB, MAX and MAND Masks Added to AMASSS

- AMASSS/AMASSS.py
Allow the user to download all new models (including the different masks segmentation models with Cranial Base, Mandible or Maxilla models)
@juanprietob
> ENH: Link changed to download all new models

- AMASSS/AMASSS.py
- AMASSS/Resources/UI/AMASSS.ui
- AMASSS_CLI/AMASSS_CLI.py
Implementation of ModelMaker module in AMASSS (use segmentation files as input to produce vtk files as output) 
Thanks @juanprietob
> ENH: ModelMaker in AMASSS

- AMASSS/AMASSS.py
- AMASSS_CLI/AMASSS_CLI.py
Correction of different issues concerning vtk files generation in AMASSS and ModelMaker extension
Thanks @juanprietob
> Fix: Correct VTK files generation for AMASSS

- ALI/ALI.py
- ALI/Resources/UI/ALI.ui
- ALI_CBCT/ALI_CBCT.py
- ALI_CBCT/ALI_CBCT.xml
- AMASSS/AMASSS.py
- AMASSS/Resources/UI/AMASSS.ui
- AMASSS_CLI/AMASSS_CLI.py
- AMASSS_CLI/AMASSS_CLI.xml
> ENH: Dicom Files as input for AMASSS and ALI_CBCT 

- ALI_CBCT/ALI_CBCT.py
- AMASSS_CLI/AMASSS_CLI.py
To avoid endless searching time for landmarks and to change monai import
Thanks @juanprietob
> BUG: Landmark Identification failure and Monai Version

- ALI_CBCT/ALI_CBCT.py
- AMASSS_CLI/AMASSS_CLI.py
- ASO/ASO.py
- ASO/Methode/CBCT.py
- ASO/Methode/Methode.py
- ASO/Resources/UI/ASO.ui
- ASO_CBCT/ASO_CBCT_utils/Net.py
- ASO_CBCT/ASO_CBCT_utils/__init__.py
- ASO_CBCT/ASO_CBCT_utils/utils.py
- ASO_CBCT/PRE_ASO_CBCT/PRE_ASO_CBCT.py
- ASO_CBCT/PRE_ASO_CBCT/PRE_ASO_CBCT.xml
- ASO_CBCT/SEMI_ASO_CBCT/SEMI_ASO_CBCT.py
PR to correct some bugs and to implement for ASO dicom as input
Thanks, @juanprietob
> Different bug fix for ALI, AMASSS and DCM as input for ASO

- AMASSS/AMASSS.py
- AMASSS_CLI/AMASSS_CLI.py
- ASO_CBCT/ASO_CBCT_utils/__init__.py
- ASO_CBCT/ASO_CBCT_utils/utils.py
- ASO_CBCT/PRE_ASO_CBCT/PRE_ASO_CBCT.py
- ASO_CBCT/SEMI_ASO_CBCT/SEMI_ASO_CBCT.py
CPU usage useless for process time purposes and some bug fixes 
Thanks @juanprietob
> BUG: issue #33 solved and some minor bug fix

- AREG/AREG.py
- AREG/AREG_Methode/CBCT.py
- AREG/Resources/UI/AREG.ui
- AREG_CBCT/AREG_CBCT.py
- AREG_CBCT/AREG_CBCT.xml
- AREG_CBCT/AREG_CBCT_utils/utils.py
- ASO/ASO.py
PR to fix the computation of AREG CBCT on WIndows OS (by changing the registration framework: simpleelastix --> itk-elastix)
Thanks @juanprietob @allemangD
> FIX: AREG CBCT for Windows OS

- ALI/ALI.py
- AutoCrop3D/Crop_Volumes_CLI/AutoCrop3D_CLI.py
- AutoCrop3D/Crop_Volumes_UI/AutoCrop3D.py
Hello @allemangD 
We saw that the last trained models for ALI CBCT weren't deployed so I added a release in the repository and I updated the code to get the access from slicer.
> Update trained models for ALI CBCT

- AMASSS/AMASSS.py
Hello @allemangD 
I changed the way the installation is done for torch in windows to troubleshoot the issue #81.
Thanks,
> BUG: Fix AMASSS installation of torch for windows system

- ALI/ALI.py
HI @allemangD 
I just add an if to check if the user is trying to run ALI_IOS on windows, it's to fix a bug with the installation librairies :)
Thank you !
> FIX BUG : librairies instllation

- AREG/AREG.py
- AREG/Resources/UI/AREG.ui
Hello @allemangD 
I changed the way Pytorch3D is installed by adding the installation of torch and splitted the "list_libs" according to the system used.
Thanks
> BUG: AREG windows installation + add a line to indicate that packages are being installed

- AMASSS/AMASSS.py
- AMASSS/Resources/UI/AMASSS.ui
Hello @allemangD 
We received some feedbacks about my last change about the installation of torch in windows.
I added some test about the cuda version to download the right version for torch, torchvision and torchaudio and I fixed the error of the issue #81.
Hope this one is the one :)
Thank you!
> BUG: fix packages installation for windows system of AMASSS

- ALI/ALI.py
- ALI/tempo.txt
Hi @allemangD !
Just a fix, some import was missing. Can you merge it ? 
Thank you !
Gaelle
> FIX : missing import

- ALI/ALI.py
Hi @allemangD !
I've made  the same changes as I did for SlicerDentalModelSeg. I'm now giving the pythonpath of Slicer to WSL to be able to run the file ALI_IOS_WSL.py. Can you check this and if it's ok merge it ? 
Thank you !
Gaelle
> ENH : running ALI on windows with pythonpath

- AREG/AREG.py
- ASO/ASO.py
- FlexReg/FlexReg.py
- MRI2CBCT/MRI2CBCT.py
- MRI2CBCT/Resources/UI/MRI2CBCT.ui
- MRI2CBCT_CLI/ImportLibrary.cmake
- MRI2CBCT_CLI/MRI2CBCT_CLI_utils/AREG_MRI.py
- MRI2CBCT_CLI/MRI2CBCT_CLI_utils/resample_create_csv.py
- MRI2CBCT_CLI/MRI2CBCT_REG/MRI2CBCT_REG.py
Hi @allemangD !
I forgot to manage the pip install in the first pull request so I'm doing it now
Thank you :)
> BUG : fix import function

- DOCShapeAXI/DOCShapeAXI.py
- DOCShapeAXI/Resources/UI/DOCShapeAXI.ui
- DOCShapeAXI_CLI/DOCShapeAXI_CLI.py
Hi @allemangD, 
There were few bugs in the DOC-ShapeAXI extension, mainly due to variable naming issues, missing text in time label and json file. I also remove a confusing message about the slicerconda installation displayed in the UI.
Thanks, 
Lucie
> BUG: multiples fix regarding the setup and running the extension

- AutoMatrix/AutoMatrix_Method/General_tools.py
- Automatrix_CLI/Automatrix_CLI.py
Added support for `.nii` files in addition to the previously supported `.nii.gz` format.
> ENH: Added support to .nii files

- AREG/AREG.py
- AREG/AREG_Method/IOS.py
- AREG_IOS/AREG_IOS.py
- AREG_IOS/AREG_IOS.xml
- AREG_IOS/AREG_IOS_utils/__init__.py
- AREG_IOS/AREG_IOS_utils/transformation.py
- ASO_IOS/ASO_IOS_utils/__init__.py
- ASO_IOS/ASO_IOS_utils/utils.py
- ASO_IOS/PRE_ASO_IOS/PRE_ASO_IOS.py
- FlexReg/FlexReg.py
- FlexReg_CLI/FlexReg_CLI.py
This PR adds support for saving the computed transformation matrices in the following IOS tools:
- AREG
- ASO
- FlexReg
> Add matrix saving functionality to AREG, ASO, and FlexReg IOS tools

- MRI2CBCT_CLI/MRI2CBCT_REG/MRI2CBCT_REG.py
Updated MRI2CBCT Registration to use the CBCT mask for the MRI.
> FIX: Applied MASK to MRI
